CREATE DATABASE EduSys
GO
USE EduSys
GO
CREATE TABLE NHANVIEN
(
	MANV NVARCHAR(50) NOT NULL PRIMARY KEY,
	MATKHAU NVARCHAR(50) NOT NULL,
	HoTen NVARCHAR(50) NOT NULL,
	VaiTro BIT NOT NULL,
)
GO
CREATE TABLE CHUYENDE
(
	MaCD NCHAR(5) NOT NULL PRIMARY KEY,
	TenCD NVARCHAR(50) NOT NULL,
	HocPhi FLOAT NOT NULL,
	ThoiLuong INT NOT NULL,
	Hinh NVARCHAR(50) NOT NULL,
	MoTa NVARCHAR(300) NOT NULL
)
GO
CREATE TABLE KHOAHOC
(
	MaKH INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	MaCD NCHAR(5) NOT NULL FOREIGN KEY REFERENCES CHUYENDE(MaCD) ON DELETE NO ACTION ON UPDATE CASCADE,
	HocPhi FLOAT NOT NULL,
	ThoiLuong INT NOT NULL,
	NgayKG DATE NOT NULL,
	GhiChu NVARCHAR(50),
	MaNV NVARCHAR(50) NOT NULL FOREIGN KEY REFERENCES NHANVIEN(MANV) ON DELETE NO ACTION ON UPDATE CASCADE,
	NgayTao DATE NOT NULL
)
GO
CREATE TABLE NGUOIHOC
(
	MaNH NCHAR(7) NOT NULL PRIMARY KEY,
	HoTen NVARCHAR(50) NOT NULL,
	NgaySinh DATE NOT NULL,
	GioiTinh BIT NOT NULL,
	DienThoai NVARCHAR(50) NOT NULL,
	Email NVARCHAR(50) NOT NULL,
	GhiChu NVARCHAR(MAX) NULL,
	MaNV NVARCHAR(50) NOT NULL FOREIGN KEY REFERENCES NHANVIEN(MANV) ON DELETE NO ACTION ON UPDATE CASCADE,
	NgayDK DATE NOT NULL
)
GO
CREATE TABLE HOCVIEN
(
	 MaHV INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	 MaKH INT NOT NULL FOREIGN KEY REFERENCES KHOAHOC(MaKH) ON DELETE NO ACTION ON UPDATE CASCADE,
	 MaNH NCHAR(7) NOT NULL FOREIGN KEY REFERENCES NGUOIHOC(MaNH),
	 Diem FLOAT NOT NULL
)
GO
ALTER TABLE [dbo].HOCVIEN  WITH CHECK ADD  CONSTRAINT [FK_HocVien_NguoiHoc] FOREIGN KEY([MaNH])
REFERENCES [dbo].NGUOIHOC ([MaNH])
ON DELETE CASCADE

--tạo thủ tục lưu bảng điểm
GO
CREATE PROC [dbo].[sp_BangDiem](@MaKH INT)
AS BEGIN
	SELECT
		nh.MaNH,
		nh.HoTen,
		hv.Diem
	FROM HOCVIEN hv
		JOIN NGUOIHOC nh ON nh.MaNH=hv.MaNH
	WHERE hv.MaKH = @MaKH
	ORDER BY hv.Diem DESC
END
GO
--tạo thủ tục lưu thống kê điểm
CREATE PROC [dbo].[sp_ThongKeDiem]
AS BEGIN
	SELECT
		TenCD ChuyenDe,
		COUNT(MaHV) SoHV,
		MIN(Diem) ThapNhat,
		MAX(Diem) CaoNhat,
		AVG(Diem) TrungBinh
	FROM KhoaHoc kh
		JOIN HocVien hv ON kh.MaKH=hv.MaKH
		JOIN ChuyenDe cd ON cd.MaCD=kh.MaCD
	GROUP BY TenCD
END
GO
--tạo thủ tục lưu thống kê điểm
CREATE PROC [dbo].[sp_ThongKeDoanhThu](@Year INT)
AS BEGIN
	SELECT
		TenCD ChuyenDe,
		COUNT(DISTINCT kh.MaKH) SoKH,
		COUNT(hv.MaHV) SoHV,
		SUM(kh.HocPhi) DoanhThu,
		MIN(kh.HocPhi) ThapNhat,
		MAX(kh.HocPhi) CaoNhat,
		AVG(kh.HocPhi) TrungBinh
	FROM KHOAHOC kh
		JOIN HOCVIEN hv ON kh.MaKH=hv.MaKH
		JOIN CHUYENDE cd ON cd.MaCD=kh.MaCD
	WHERE YEAR(NgayKG) = @Year
	GROUP BY TenCD
END
GO
--tạo thủ tục lưu thống kê người học
CREATE PROC [dbo].[sp_ThongKeNguoiHoc]
AS BEGIN
	SELECT
		YEAR(NgayDK) Nam,
		COUNT(*) SoLuong,
		MIN(NgayDK) DauTien,
		MAX(NgayDK) CuoiCung
	FROM NGUOIHOC
	GROUP BY YEAR(NgayDK)
END
GO

SELECT * FROM NhanVien
SELECT * FROM HoCvIEN

--Nhân viên
INSERT INTO [dbo].[NHANVIEN]([MANV],[MATKHAU],[HoTen],[VaiTro],[SDT]) VALUES (?,?,?,?,?)
UPDATE NHANVIEN SET MATKHAU = ?, HoTen = ?, VaiTro = ?, SDT = ? WHERE  MANV = ?
DELETE FROM NHANVIEN WHERE  MANV = ?
SELECT * FROM NhanVien
SELECT * FROM NhanVien WHERE  MANV = ? and MATKHAU = ?