CREATE DATABASE EduSys
GO
USE EduSys
GO
CREATE TABLE NHANVIEN
(
	MANV NVARCHAR(50) NOT NULL PRIMARY KEY,
	MATKHAU NVARCHAR(50) NOT NULL,
	HoTen NVARCHAR(50) NOT NULL,
	VaiTro BIT NOT NULL,
)
GO
CREATE TABLE CHUYENDE
(
	MaCD NCHAR(5) NOT NULL PRIMARY KEY,
	TenCD NVARCHAR(50) NOT NULL,
	HocPhi FLOAT NOT NULL,
	ThoiLuong INT NOT NULL,
	Hinh NVARCHAR(50) NOT NULL,
	MoTa NVARCHAR(300) NOT NULL
)
GO
CREATE TABLE KHOAHOC
(
	MaKH INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	MaCD NCHAR(5) NOT NULL FOREIGN KEY REFERENCES CHUYENDE(MaCD) ON DELETE NO ACTION ON UPDATE CASCADE,
	HocPhi FLOAT NOT NULL,
	ThoiLuong INT NOT NULL,
	NgayKG DATE NOT NULL,
	GhiChu NVARCHAR(50),
	MaNV NVARCHAR(50) NOT NULL FOREIGN KEY REFERENCES NHANVIEN(MANV) ON DELETE NO ACTION ON UPDATE CASCADE,
	NgayTao DATE NOT NULL
)
GO
CREATE TABLE NGUOIHOC
(
	MaNH NCHAR(7) NOT NULL PRIMARY KEY,
	HoTen NVARCHAR(50) NOT NULL,
	NgaySinh DATE NOT NULL,
	GioiTinh BIT NOT NULL,
	DienThoai NVARCHAR(50) NOT NULL,
	Email NVARCHAR(50) NOT NULL,
	GhiChu NVARCHAR(MAX) NULL,
	MaNV NVARCHAR(50) NOT NULL FOREIGN KEY REFERENCES NHANVIEN(MANV) ON DELETE NO ACTION ON UPDATE CASCADE,
	NgayDK DATE NOT NULL
)
GO
CREATE TABLE HOCVIEN
(
	 MaHV INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	 MaKH INT NOT NULL FOREIGN KEY REFERENCES KHOAHOC(MaKH) ON DELETE NO ACTION ON UPDATE CASCADE,
	 MaNH NCHAR(7) NOT NULL FOREIGN KEY REFERENCES NGUOIHOC(MaNH),
	 Diem FLOAT NOT NULL
)

ALTER TABLE [dbo].HOCVIEN  WITH CHECK ADD  CONSTRAINT [FK_HocVien_NguoiHoc] FOREIGN KEY([MaNH])
REFERENCES [dbo].NGUOIHOC ([MaNH])
ON DELETE CASCADE
