/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

import com.edusys.dao.ChuyenDeDAO;
import com.edusys.dao.KhoaHocDAO;
import com.edusys.entity.ChuyenDe;
import com.edusys.entity.KhoaHoc;
import com.edusys.utils.Auth;
import com.edusys.utils.DateHelper;
import com.edusys.utils.MessegerHelper;
import com.sun.mail.imap.ACL;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author XUÂN THÀNH
 */
public class QLKhoaHocJPanel extends javax.swing.JPanel {

    private DefaultComboBoxModel<ChuyenDe> dcbm;
    private DefaultTableModel dtm;
    private ChuyenDeDAO cddao;
    private KhoaHocDAO khdao;
    private int index;

    public QLKhoaHocJPanel() {
        initComponents();

        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCardQLKhoaHoc = new javax.swing.JPanel();
        pnlQLKHTop = new javax.swing.JPanel();
        lblQLKhoaHocTitle = new javax.swing.JLabel();
        pnlChuyenDe = new javax.swing.JPanel();
        cbbChuyenDe = new javax.swing.JComboBox<>();
        btnLoadCD = new javax.swing.JButton();
        pnlQLKH = new javax.swing.JPanel();
        pnlQLKH2 = new javax.swing.JPanel();
        pnlQLKHInput = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        txtTenCD = new javax.swing.JTextField();
        lblTenCD = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblHocPhi = new javax.swing.JLabel();
        txtHocPhi = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txtTenNguoiTao = new javax.swing.JTextField();
        lblTenNguoiTao = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        txtNgayKG = new javax.swing.JTextField();
        lblNgayKG = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtThoiLuong = new javax.swing.JTextField();
        lblThoiLuong = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        txtNgayTao = new javax.swing.JTextField();
        lblNgayTao = new javax.swing.JLabel();
        pnlButton = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        btnFirst = new javax.swing.JButton();
        btnPre = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhoaHoc = new javax.swing.JTable();
        pnlGhiChu = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();

        pnlCardQLKhoaHoc.setBackground(new java.awt.Color(34, 40, 44));
        pnlCardQLKhoaHoc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pnlCardQLKhoaHocFocusGained(evt);
            }
        });
        pnlCardQLKhoaHoc.setLayout(new java.awt.BorderLayout());

        pnlQLKHTop.setBackground(new java.awt.Color(34, 40, 44));
        pnlQLKHTop.setPreferredSize(new java.awt.Dimension(891, 100));
        pnlQLKHTop.setLayout(new java.awt.BorderLayout());

        lblQLKhoaHocTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblQLKhoaHocTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblQLKhoaHocTitle.setText("QUẢN LÝ KHÓA HỌC");
        lblQLKhoaHocTitle.setToolTipText("");
        lblQLKhoaHocTitle.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblQLKhoaHocTitle.setPreferredSize(new java.awt.Dimension(34, 40));
        lblQLKhoaHocTitle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblQLKhoaHocTitleFocusGained(evt);
            }
        });
        pnlQLKHTop.add(lblQLKhoaHocTitle, java.awt.BorderLayout.NORTH);

        pnlChuyenDe.setBackground(new java.awt.Color(34, 40, 44));
        pnlChuyenDe.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "CHUYÊN ĐỀ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(255, 102, 102))); // NOI18N

        cbbChuyenDe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbChuyenDeItemStateChanged(evt);
            }
        });

        btnLoadCD.setText("Load Chuyên Đề");
        btnLoadCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadCDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlChuyenDeLayout = new javax.swing.GroupLayout(pnlChuyenDe);
        pnlChuyenDe.setLayout(pnlChuyenDeLayout);
        pnlChuyenDeLayout.setHorizontalGroup(
            pnlChuyenDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChuyenDeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbbChuyenDe, 0, 674, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addComponent(btnLoadCD)
                .addGap(71, 71, 71))
        );
        pnlChuyenDeLayout.setVerticalGroup(
            pnlChuyenDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChuyenDeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlChuyenDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbChuyenDe)
                    .addComponent(btnLoadCD))
                .addContainerGap())
        );

        pnlQLKHTop.add(pnlChuyenDe, java.awt.BorderLayout.CENTER);

        pnlCardQLKhoaHoc.add(pnlQLKHTop, java.awt.BorderLayout.PAGE_START);

        pnlQLKH.setBackground(new java.awt.Color(34, 40, 44));

        pnlQLKH2.setBackground(new java.awt.Color(34, 40, 44));

        pnlQLKHInput.setBackground(new java.awt.Color(34, 40, 44));
        pnlQLKHInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));
        pnlQLKHInput.setLayout(new java.awt.GridLayout(0, 2));

        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));
        jPanel16.setLayout(new java.awt.GridLayout(3, 0));

        jPanel15.setBackground(new java.awt.Color(34, 40, 44));

        txtTenCD.setEditable(false);
        txtTenCD.setBackground(new java.awt.Color(34, 40, 44));
        txtTenCD.setForeground(new java.awt.Color(255, 0, 0));

        lblTenCD.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lblTenCD.setForeground(new java.awt.Color(255, 255, 255));
        lblTenCD.setText("Chuyên Đề");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenCD)
                    .addComponent(lblTenCD, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTenCD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenCD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel16.add(jPanel15);

        jPanel3.setBackground(new java.awt.Color(34, 40, 44));

        lblHocPhi.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lblHocPhi.setForeground(new java.awt.Color(255, 255, 255));
        lblHocPhi.setText("Học Phí");

        txtHocPhi.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHocPhi, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                    .addComponent(txtHocPhi))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHocPhi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHocPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel16.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(34, 40, 44));

        txtTenNguoiTao.setEditable(false);

        lblTenNguoiTao.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lblTenNguoiTao.setForeground(new java.awt.Color(255, 255, 255));
        lblTenNguoiTao.setText("Người Tạo");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenNguoiTao)
                    .addComponent(lblTenNguoiTao, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTenNguoiTao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenNguoiTao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel16.add(jPanel4);

        pnlQLKHInput.add(jPanel16);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));
        jPanel2.setLayout(new java.awt.GridLayout(3, 0));

        jPanel9.setBackground(new java.awt.Color(34, 40, 44));

        lblNgayKG.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lblNgayKG.setForeground(new java.awt.Color(255, 255, 255));
        lblNgayKG.setText("Khai Giảng");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNgayKG, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                    .addComponent(txtNgayKG, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNgayKG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNgayKG, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        jPanel2.add(jPanel9);

        jPanel5.setBackground(new java.awt.Color(34, 40, 44));

        txtThoiLuong.setEditable(false);

        lblThoiLuong.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lblThoiLuong.setForeground(new java.awt.Color(255, 255, 255));
        lblThoiLuong.setText("Thời Lượng(giờ)");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblThoiLuong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                    .addComponent(txtThoiLuong))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblThoiLuong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtThoiLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        jPanel2.add(jPanel5);

        jPanel7.setBackground(new java.awt.Color(34, 40, 44));

        txtNgayTao.setEditable(false);

        lblNgayTao.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lblNgayTao.setForeground(new java.awt.Color(255, 255, 255));
        lblNgayTao.setText("Ngày Tạo");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNgayTao, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                    .addComponent(txtNgayTao))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNgayTao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel7);

        pnlQLKHInput.add(jPanel2);

        pnlButton.setLayout(new java.awt.GridLayout(0, 2));

        jPanel12.setBackground(new java.awt.Color(34, 40, 44));

        btnThem.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setPreferredSize(new java.awt.Dimension(65, 41));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel12.add(btnThem);

        btnSua.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setPreferredSize(new java.awt.Dimension(65, 41));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel12.add(btnSua);

        btnXoa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setPreferredSize(new java.awt.Dimension(65, 41));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel12.add(btnXoa);

        btnMoi.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnMoi.setText("Mới");
        btnMoi.setPreferredSize(new java.awt.Dimension(65, 41));
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });
        jPanel12.add(btnMoi);

        pnlButton.add(jPanel12);

        jPanel11.setBackground(new java.awt.Color(34, 40, 44));

        btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/rnd_br_first.png"))); // NOI18N
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        jPanel11.add(btnFirst);

        btnPre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/rnd_br_prev.png"))); // NOI18N
        btnPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreActionPerformed(evt);
            }
        });
        jPanel11.add(btnPre);

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/rnd_br_next.png"))); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel11.add(btnNext);

        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/rnd_br_last.png"))); // NOI18N
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        jPanel11.add(btnLast);

        pnlButton.add(jPanel11);

        tblKhoaHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ KH", "THỜI LƯỢNG", "HỌC PHÍ", "Khai Giảng", "TẠO BỞI", "NGÀY TẠO", "GHICHU"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhoaHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhoaHocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhoaHoc);
        if (tblKhoaHoc.getColumnModel().getColumnCount() > 0) {
            tblKhoaHoc.getColumnModel().getColumn(6).setMinWidth(0);
            tblKhoaHoc.getColumnModel().getColumn(6).setPreferredWidth(0);
            tblKhoaHoc.getColumnModel().getColumn(6).setMaxWidth(0);
        }

        pnlGhiChu.setBackground(new java.awt.Color(34, 40, 44));
        pnlGhiChu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ghi Chú", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Arial", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane2.setViewportView(txtGhiChu);

        javax.swing.GroupLayout pnlGhiChuLayout = new javax.swing.GroupLayout(pnlGhiChu);
        pnlGhiChu.setLayout(pnlGhiChuLayout);
        pnlGhiChuLayout.setHorizontalGroup(
            pnlGhiChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        pnlGhiChuLayout.setVerticalGroup(
            pnlGhiChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGhiChuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnlQLKH2Layout = new javax.swing.GroupLayout(pnlQLKH2);
        pnlQLKH2.setLayout(pnlQLKH2Layout);
        pnlQLKH2Layout.setHorizontalGroup(
            pnlQLKH2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQLKH2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQLKH2Layout.createSequentialGroup()
                .addGroup(pnlQLKH2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlGhiChu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlQLKHInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        pnlQLKH2Layout.setVerticalGroup(
            pnlQLKH2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQLKH2Layout.createSequentialGroup()
                .addComponent(pnlQLKHInput, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlQLKHLayout = new javax.swing.GroupLayout(pnlQLKH);
        pnlQLKH.setLayout(pnlQLKHLayout);
        pnlQLKHLayout.setHorizontalGroup(
            pnlQLKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 913, Short.MAX_VALUE)
            .addGroup(pnlQLKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlQLKHLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pnlQLKH2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        pnlQLKHLayout.setVerticalGroup(
            pnlQLKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
            .addGroup(pnlQLKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlQLKHLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlQLKH2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pnlCardQLKhoaHoc.add(pnlQLKH, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 913, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlCardQLKhoaHoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlCardQLKhoaHoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbbChuyenDeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbChuyenDeItemStateChanged
        ChuyenDe cd = (ChuyenDe) cbbChuyenDe.getSelectedItem();
        this.txtTenCD.setText(cd.getTenCD());
        this.txtHocPhi.setText(cd.getHocPhi() + "");
        this.txtThoiLuong.setText(cd.getThoiLuong() + "");
        this.txtGhiChu.setText(cd.getMoTa());
        loadDataToTable(cd.getMaCD());
    }//GEN-LAST:event_cbbChuyenDeItemStateChanged

    private void pnlCardQLKhoaHocFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pnlCardQLKhoaHocFocusGained
    }//GEN-LAST:event_pnlCardQLKhoaHocFocusGained

    private void lblQLKhoaHocTitleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblQLKhoaHocTitleFocusGained
    }//GEN-LAST:event_lblQLKhoaHocTitleFocusGained

    private void btnLoadCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadCDActionPerformed
        this.loadDataToCBB();
        ChuyenDe cd = (ChuyenDe) this.cbbChuyenDe.getSelectedItem();
        loadDataToTable(cd.getMaCD());
    }//GEN-LAST:event_btnLoadCDActionPerformed

    private void tblKhoaHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhoaHocMouseClicked
        if (mouseClicked())
            return;
    }//GEN-LAST:event_tblKhoaHocMouseClicked

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        first();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreActionPerformed
        prev();
    }//GEN-LAST:event_btnPreActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        last();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        clearForm();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        ChuyenDe cd = (ChuyenDe) this.cbbChuyenDe.getSelectedItem();
        if (checkForm()) {
            return;
        }

        try {
            this.khdao.insert(getForm());
            MessegerHelper.alert("Thêm thành công", this);
            this.loadDataToTable(cd.getMaCD());
            this.index = tblKhoaHoc.getRowCount() - 1;
            this.tblKhoaHoc.setRowSelectionInterval(index, index);
            showForm(index);
        } catch (Exception ex) {
            ex.printStackTrace();
            MessegerHelper.errorMesseger(new StringBuilder("Lỗi truy vấn"), this);
            return;
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (checkForm()) {
            return;
        }
        KhoaHoc kh = getForm();
        kh.setMaKH((int) this.tblKhoaHoc.getValueAt(index, 0));

        if (MessegerHelper.confirm(this, "Bạn có muốn sửa khóa học có mã " + kh.getMaKH() + " không?")) {
            try {
                this.khdao.update(kh);
                MessegerHelper.alert("Sửa thành công", this);
                this.tblKhoaHoc.setValueAt(kh.getThoiLuong(), index, 1);
                this.tblKhoaHoc.setValueAt(kh.getHocPhi(), index, 2);
                this.tblKhoaHoc.setValueAt(DateHelper.toString(kh.getNgayKG(), "dd/MM/yyyy"), index, 3);
                this.tblKhoaHoc.setValueAt(kh.getMaNV(), index, 4);
                this.tblKhoaHoc.setValueAt(DateHelper.toString(kh.getNgayTao(), "dd/MM/yyyy"), index, 5);
                this.tblKhoaHoc.setValueAt(kh.getGhiChu(), index, 6);
            } catch (Exception e) {
                MessegerHelper.errorMesseger(new StringBuilder("Lỗi truy vấn!"), this);
                e.printStackTrace();
                return;
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
       int makh = (int) this.tblKhoaHoc.getValueAt(index, 0);
        if (MessegerHelper.confirm(this, "Bạn có muốn xóa khóa học có mã: " + makh + " này không?")) {
            try {
                this.khdao.delete(makh);
                MessegerHelper.alert("Xóa thành công", this);
                this.dtm.removeRow(index);
                showForm(index > tblKhoaHoc.getRowCount() - 1 ? tblKhoaHoc.getRowCount() - 1 : index);
            } catch (Exception ex) {
                MessegerHelper.errorMesseger(new StringBuilder("Lỗi truy vấn!"), this);
                ex.printStackTrace();
                return;
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnLoadCD;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPre;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbChuyenDe;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblHocPhi;
    private javax.swing.JLabel lblNgayKG;
    private javax.swing.JLabel lblNgayTao;
    private javax.swing.JLabel lblQLKhoaHocTitle;
    private javax.swing.JLabel lblTenCD;
    private javax.swing.JLabel lblTenNguoiTao;
    private javax.swing.JLabel lblThoiLuong;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JPanel pnlCardQLKhoaHoc;
    private javax.swing.JPanel pnlChuyenDe;
    private javax.swing.JPanel pnlGhiChu;
    private javax.swing.JPanel pnlQLKH;
    private javax.swing.JPanel pnlQLKH2;
    private javax.swing.JPanel pnlQLKHInput;
    private javax.swing.JPanel pnlQLKHTop;
    private javax.swing.JTable tblKhoaHoc;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtHocPhi;
    private javax.swing.JTextField txtNgayKG;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtTenCD;
    private javax.swing.JTextField txtTenNguoiTao;
    private javax.swing.JTextField txtThoiLuong;
    // End of variables declaration//GEN-END:variables

    public void init() {
        //khai báo chuyên đề dao
        this.cddao = new ChuyenDeDAO();
        //khai báo khóa học dao
        this.khdao = new KhoaHocDAO();

        this.dcbm = (DefaultComboBoxModel) this.cbbChuyenDe.getModel();
        this.dtm = (DefaultTableModel) this.tblKhoaHoc.getModel();

        //load dữ liệu lên combobox chuyên đề
        loadDataToCBB();
        //load dữ liệu lên bảo theo chuyên đề
        ChuyenDe cd = (ChuyenDe) this.cbbChuyenDe.getSelectedItem();
        loadDataToTable(cd.getMaCD());
    }

    public void loadDataToCBB() {
        ArrayList<ChuyenDe> listCD = new ArrayList<>();
        this.dcbm.removeAllElements();
        this.cbbChuyenDe.removeAllItems();
        try {
//        this.dcbm = (DefaultComboBoxModel)this.cbbChuyenDe.getModel();
            listCD = this.cddao.selectALL();
            for (ChuyenDe cd : listCD) {
                this.dcbm.addElement(cd);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    public void loadDataToTable(String maCD) {
        ArrayList<KhoaHoc> listKH = new ArrayList<>();
        this.dtm.setRowCount(0);
        try {
            listKH = this.khdao.selectByQuery("SELECTBYMACD", maCD);
            if (listKH.size() <= 0) {
                clearForm();
                return;
            }
            for (KhoaHoc kh : listKH) {
                setDataRow(kh);
            }
            this.index = 0;
            updateStatus();
            showForm(index);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void setDataRow(KhoaHoc kh) {
        dtm.addRow(new Object[]{
            kh.getMaKH(),
            kh.getThoiLuong(),
            kh.getHocPhi(),
            DateHelper.toString(kh.getNgayKG(), "dd/MM/yyyy"),
            kh.getMaNV(),
            DateHelper.toString(kh.getNgayTao(), "dd/MM/yyyy"),
            kh.getGhiChu()
        });
    }

    private void updateStatus() {
        //cập nhập trạng thái cho các button điều hướng
        boolean first = (this.index <= 0);
        boolean last = (this.index == tblKhoaHoc.getRowCount() - 1);
        this.btnSua.setEnabled(this.index >= 0);
        this.btnXoa.setEnabled(this.index >= 0);
        this.btnFirst.setEnabled(!first);
        this.btnPre.setEnabled(!first);
        this.btnLast.setEnabled(!last);
        this.btnNext.setEnabled(!last);
        if (index == -1) {
            this.tblKhoaHoc.setRowSelectionAllowed(false);
        } else {
            this.tblKhoaHoc.setRowSelectionAllowed(true);
        }
    }

    private void showForm(int i) {
        //hiển thị dữ liệu lên form tương ứng
        this.txtTenNguoiTao.setText(tblKhoaHoc.getValueAt(i, 4) + "");
        this.txtNgayKG.setText(tblKhoaHoc.getValueAt(i, 3) + "");
        this.txtNgayTao.setText(tblKhoaHoc.getValueAt(i, 5) + "");
        this.txtGhiChu.setText(tblKhoaHoc.getValueAt(i, 6) + "");
        this.tblKhoaHoc.setRowSelectionInterval(i, i);
    }

    private KhoaHoc getForm() {
        ChuyenDe cd = (ChuyenDe) this.cbbChuyenDe.getSelectedItem();
        String maCD = cd.getMaCD();
        float hocPhi = cd.getHocPhi();
        int thoiLuong = cd.getThoiLuong();
        Date ngayKG = DateHelper.toDate(this.txtNgayKG.getText(), "dd/MM/yyyy");
        String ghiChu = this.txtGhiChu.getText();
        String maNV = Auth.nguoiDungHienTai.getMaNV();
        Date ngayTao = DateHelper.toDate(DateHelper.toString(new Date(), "dd/MM/yyyy"), "dd/MM/yyyy");;
        return new KhoaHoc(maCD, hocPhi, thoiLuong, ngayKG, ghiChu, maNV, ngayTao);
    }

    private void clearForm() {
        //xóa trắng form
        this.txtNgayKG.setText("");
        this.txtGhiChu.setText("");
        this.txtNgayTao.setText("");
        this.txtTenNguoiTao.setText("");
        this.index = -1;
        updateStatus();
    }

    private boolean mouseClicked() {
        //xử lý sưk kiện click lên table
        this.index = tblKhoaHoc.getSelectedRow();
        updateStatus();
        if (index == -1) {
            return true;
        }
        showForm(index);
        return false;
    }

    private void next() {
        index++;
        updateStatus();
        showForm(index);
    }

    private void last() {
        index = tblKhoaHoc.getRowCount() - 1;
        updateStatus();
        showForm(index);
    }

    private void prev() {
        index--;
        updateStatus();
        showForm(index);
    }

    private void first() {
        index = 0;
        updateStatus();
        showForm(index);
    }

    private boolean checkForm() {
        StringBuilder loi = new StringBuilder();
        if (this.txtNgayKG.getText().trim().isEmpty()) {
            loi.append("Bạn phải nhập ngày khai giảng!");
        } else {
            try {
                Date nkg = DateHelper.toDate(txtNgayKG.getText(), "dd/MM/yyyy");
                Date now = new Date();
                if (nkg.before(now)) {
                    loi.append("Ngày khai giảng phải là ngày sau hiện tại");
                }
            } catch (Exception e) {
                e.printStackTrace();
                loi.append("Sai định dạng(dd/MM/yyyy)");
            }
        }
        //hiển thị thông báo lỗi
        if (loi.length() > 0) {
            MessegerHelper.errorMesseger(loi, this);
            return true;
        }
        return false;
    }
}
