/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

import com.edusys.dao.NhanVienDao;
import com.edusys.entity.NhanVien;
import com.edusys.utils.MessegerHelper;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

/**
 *
 * @author XUÂN THÀNH
 */
public class QuenMatKhauJDialog extends javax.swing.JDialog {

    private NhanVienDao dao;
    private NhanVien nv;
    private String codeSMS;

    public QuenMatKhauJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCardsQMK = new javax.swing.JPanel();
        pnlQuenMK = new javax.swing.JPanel();
        lblQuayLai = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnDongY = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();
        pnlMaOTP = new javax.swing.JPanel();
        lblQuayLai1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaOTP = new javax.swing.JTextField();
        btnGuiLai = new javax.swing.JButton();
        btnTiepTuc = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblBackground1 = new javax.swing.JLabel();
        pnlDoiMK = new javax.swing.JPanel();
        lblQuayLai2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnDongYDoiMK = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtMatKhauMoi = new javax.swing.JPasswordField();
        txtMatKhauMoi2 = new javax.swing.JPasswordField();
        lblBackground2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlCardsQMK.setLayout(new java.awt.CardLayout());

        pnlQuenMK.setBackground(new java.awt.Color(153, 153, 153));
        pnlQuenMK.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQuayLai.setBackground(new java.awt.Color(51, 51, 51));
        lblQuayLai.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblQuayLai.setForeground(new java.awt.Color(255, 255, 255));
        lblQuayLai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/br_prev32.png"))); // NOI18N
        lblQuayLai.setText("Quay lại");
        lblQuayLai.setOpaque(true);
        lblQuayLai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuayLaiMouseClicked(evt);
            }
        });
        pnlQuenMK.add(lblQuayLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("QUÊN MẬT KHẨU?");
        pnlQuenMK.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 340, 60));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nhập tài khoản của bạn:");
        pnlQuenMK.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 300, 40));

        txtTaiKhoan.setBackground(new java.awt.Color(51, 51, 51));
        txtTaiKhoan.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txtTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        txtTaiKhoan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTaiKhoan.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        txtTaiKhoan.setOpaque(false);
        pnlQuenMK.add(txtTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 420, 50));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nhập email của bạn:");
        pnlQuenMK.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 300, 40));

        txtEmail.setBackground(new java.awt.Color(51, 51, 51));
        txtEmail.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        txtEmail.setOpaque(false);
        pnlQuenMK.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 420, 50));

        btnDongY.setBackground(new java.awt.Color(51, 51, 51));
        btnDongY.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnDongY.setForeground(new java.awt.Color(255, 255, 255));
        btnDongY.setText("Đồng ý");
        btnDongY.setOpaque(false);
        btnDongY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongYActionPerformed(evt);
            }
        });
        pnlQuenMK.add(btnDongY, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 330, 80));

        lblBackground.setBackground(new java.awt.Color(51, 51, 51));
        lblBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/logo-small_1.png"))); // NOI18N
        lblBackground.setOpaque(true);
        pnlQuenMK.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 540, 610));

        pnlCardsQMK.add(pnlQuenMK, "QuenMK");

        pnlMaOTP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQuayLai1.setBackground(new java.awt.Color(51, 51, 51));
        lblQuayLai1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblQuayLai1.setForeground(new java.awt.Color(255, 255, 255));
        lblQuayLai1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuayLai1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/br_prev32.png"))); // NOI18N
        lblQuayLai1.setText("Quay lại");
        lblQuayLai1.setOpaque(true);
        lblQuayLai1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuayLai1MouseClicked(evt);
            }
        });
        pnlMaOTP.add(lblQuayLai1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("QUÊN MẬT KHẨU?");
        pnlMaOTP.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 340, 60));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Bạn chưa nhận được mã?");
        pnlMaOTP.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 420, 40));

        txtMaOTP.setBackground(new java.awt.Color(51, 51, 51));
        txtMaOTP.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txtMaOTP.setForeground(new java.awt.Color(255, 255, 255));
        txtMaOTP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMaOTP.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        txtMaOTP.setOpaque(false);
        pnlMaOTP.add(txtMaOTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 420, 50));

        btnGuiLai.setBackground(new java.awt.Color(51, 51, 51));
        btnGuiLai.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnGuiLai.setForeground(new java.awt.Color(255, 255, 255));
        btnGuiLai.setText("Gửi lại");
        btnGuiLai.setOpaque(false);
        btnGuiLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiLaiActionPerformed(evt);
            }
        });
        pnlMaOTP.add(btnGuiLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, 200, 60));

        btnTiepTuc.setBackground(new java.awt.Color(51, 51, 51));
        btnTiepTuc.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnTiepTuc.setForeground(new java.awt.Color(255, 255, 255));
        btnTiepTuc.setText("Tiếp tục");
        btnTiepTuc.setOpaque(false);
        btnTiepTuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiepTucActionPerformed(evt);
            }
        });
        pnlMaOTP.add(btnTiepTuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 330, 80));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nhập mã OTP chúng tôi đã gửi cho bạn:");
        pnlMaOTP.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 420, 40));

        lblBackground1.setBackground(new java.awt.Color(51, 51, 51));
        lblBackground1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBackground1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/logo-small_1.png"))); // NOI18N
        lblBackground1.setOpaque(true);
        pnlMaOTP.add(lblBackground1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 540, 610));

        pnlCardsQMK.add(pnlMaOTP, "MaOTP");

        pnlDoiMK.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQuayLai2.setBackground(new java.awt.Color(51, 51, 51));
        lblQuayLai2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblQuayLai2.setForeground(new java.awt.Color(255, 255, 255));
        lblQuayLai2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuayLai2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/br_prev32.png"))); // NOI18N
        lblQuayLai2.setText("Quay lại");
        lblQuayLai2.setOpaque(true);
        lblQuayLai2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuayLai2MouseClicked(evt);
            }
        });
        pnlDoiMK.add(lblQuayLai2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ĐỔI LẠI MẬT KHẨU");
        pnlDoiMK.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 370, 60));

        btnDongYDoiMK.setBackground(new java.awt.Color(51, 51, 51));
        btnDongYDoiMK.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnDongYDoiMK.setForeground(new java.awt.Color(255, 255, 255));
        btnDongYDoiMK.setText("Đồng ý");
        btnDongYDoiMK.setOpaque(false);
        btnDongYDoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongYDoiMKActionPerformed(evt);
            }
        });
        pnlDoiMK.add(btnDongYDoiMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 330, 80));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nhập mật khẩu mới:");
        pnlDoiMK.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 420, 40));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nhập lại mật khẩu mới:");
        pnlDoiMK.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 420, 40));

        txtMatKhauMoi.setBackground(new java.awt.Color(51, 51, 51));
        txtMatKhauMoi.setForeground(new java.awt.Color(255, 255, 255));
        txtMatKhauMoi.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        txtMatKhauMoi.setOpaque(false);
        pnlDoiMK.add(txtMatKhauMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 420, 50));

        txtMatKhauMoi2.setBackground(new java.awt.Color(51, 51, 51));
        txtMatKhauMoi2.setForeground(new java.awt.Color(255, 255, 255));
        txtMatKhauMoi2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        txtMatKhauMoi2.setOpaque(false);
        pnlDoiMK.add(txtMatKhauMoi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 420, 50));

        lblBackground2.setBackground(new java.awt.Color(51, 51, 51));
        lblBackground2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBackground2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/logo-small_1.png"))); // NOI18N
        lblBackground2.setOpaque(true);
        pnlDoiMK.add(lblBackground2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 540, 610));

        pnlCardsQMK.add(pnlDoiMK, "DoiMK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCardsQMK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCardsQMK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDongYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongYActionPerformed
        //checkRong
        StringBuilder loi = new StringBuilder();
        String manv = txtTaiKhoan.getText();
        String Email = txtEmail.getText();
        // check mã nhân viên
        if (manv.trim().isEmpty()) {
            loi.append("Không được để trống mã nhân viên\n");
        } else if (manv.length() > 50) {
            loi.append("Mã nhân viên không được quá 50 ký tự\n");
        }

        //check Email
        Pattern pEmail = Pattern.compile("^\\w+@+[a-zA-Z]+(\\.[a-zA-Z]+){1,2}$");
        if (Email.trim().isEmpty()) {
            loi.append("Không được để trống Email\n");
        } else if (!pEmail.matcher(Email).find()) {
            loi.append("Email phải đúng định dạng!\nVD: ...@gmail.com hoặc ...@fpt.edu.vn\n");
        }

        //hiển thị thông báo lỗi
        if (loi.length() > 0) {
            MessegerHelper.errorMesseger(loi, this);
            return;
        }
        nv = new NhanVien();
        try {
            nv = this.dao.selectByID(manv);
            if (nv == null) {
                MessegerHelper.errorMesseger(new StringBuilder("Tài khoản này không tồn tại!"), this);
                return;
            } else if (!nv.getEmail().equals(Email)) {
                MessegerHelper.errorMesseger(new StringBuilder("Sai email đăng ký!"), this);
                return;
            }
        } catch (Exception ex) {
            MessegerHelper.errorMesseger(new StringBuilder("Lỗi truy vấn"), this);
            return;
        }

        if (sendEmail(nv)) return;
        
        CardLayout layout = (CardLayout) pnlCardsQMK.getLayout();

        layout.show(pnlCardsQMK, "MaOTP");

    }//GEN-LAST:event_btnDongYActionPerformed

    private void lblQuayLaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuayLaiMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblQuayLaiMouseClicked

    private void lblQuayLai1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuayLai1MouseClicked
        CardLayout layout = (CardLayout) pnlCardsQMK.getLayout();

        layout.show(pnlCardsQMK, "QuenMK");
    }//GEN-LAST:event_lblQuayLai1MouseClicked

    private void btnGuiLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiLaiActionPerformed
        if (sendEmail(nv)) return;
    }//GEN-LAST:event_btnGuiLaiActionPerformed

    private void btnTiepTucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiepTucActionPerformed
        if (txtMaOTP.getText().trim().isEmpty()){
            MessegerHelper.errorMesseger(new StringBuilder("Bạn phải nhập mã OTP đã gửi đến email"), this);
            return;
        } else if (!txtMaOTP.getText().equals(codeSMS)){
            MessegerHelper.errorMesseger(new StringBuilder("Bạn đã nhập sai mã OTP!"), this);
            return;
        }
        CardLayout layout = (CardLayout) pnlCardsQMK.getLayout();

        layout.show(pnlCardsQMK, "DoiMK");
    }//GEN-LAST:event_btnTiepTucActionPerformed

    private void lblQuayLai2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuayLai2MouseClicked
        CardLayout layout = (CardLayout) pnlCardsQMK.getLayout();

        layout.show(pnlCardsQMK, "MaOTP");
    }//GEN-LAST:event_lblQuayLai2MouseClicked

    private void btnDongYDoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongYDoiMKActionPerformed
        if (txtMatKhauMoi.getText().trim().isEmpty()){
            MessegerHelper.errorMesseger(new StringBuilder("Bạn phải nhập mật khẩu mới"), this);
            return; 
        } else if (txtMatKhauMoi2.getText().trim().isEmpty()){
            MessegerHelper.errorMesseger(new StringBuilder("Bạn phải nhập lại mật khẩu mới"), this);
            return; 
        } else if (!txtMatKhauMoi2.getText().equals(txtMatKhauMoi.getText())){
            MessegerHelper.errorMesseger(new StringBuilder("Mật khẩu xác nhận không trùng nhau"), this);
            return; 
        }
        this.nv.setMatKhau(txtMatKhauMoi.getText());
        try {
            this.dao.update(nv);
            MessegerHelper.alert("Đổi mật khẩu thành công\nXin mời bạn đăng nhập lại", this);
            this.dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
            MessegerHelper.errorMesseger(new StringBuilder("Lỗi truy vấn"), this);
            return; 
        }
    }//GEN-LAST:event_btnDongYDoiMKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuenMatKhauJDialog dialog = new QuenMatKhauJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDongY;
    private javax.swing.JButton btnDongYDoiMK;
    private javax.swing.JButton btnGuiLai;
    private javax.swing.JButton btnTiepTuc;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBackground1;
    private javax.swing.JLabel lblBackground2;
    private javax.swing.JLabel lblQuayLai;
    private javax.swing.JLabel lblQuayLai1;
    private javax.swing.JLabel lblQuayLai2;
    private javax.swing.JPanel pnlCardsQMK;
    private javax.swing.JPanel pnlDoiMK;
    private javax.swing.JPanel pnlMaOTP;
    private javax.swing.JPanel pnlQuenMK;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaOTP;
    private javax.swing.JPasswordField txtMatKhauMoi;
    private javax.swing.JPasswordField txtMatKhauMoi2;
    private javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables

    private void init() {
        this.setLocationRelativeTo(null);
        this.dao = new NhanVienDao();

        btnDongY.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                btnDongY.setBackground(new Color(54, 81, 207));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                btnDongY.setBackground(new Color(51, 51, 51));
            }
        });

        lblQuayLai.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                lblQuayLai.setBackground(new Color(54, 81, 207));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                lblQuayLai.setBackground(new Color(51, 51, 51));
            }
        });
    }

    private boolean sendEmail(NhanVien nv) {
        codeSMS =  String.format("%.0f",(Math.random() * (999999 - 111110 + 1) + 111110));
        final String username = "sendmail.fpttext@gmail.com";
        final String password = "sendmail.fpttext10";

        Properties prop = new Properties();
        prop.put("mail.smtp.host", "smtp.gmail.com");
        prop.put("mail.smtp.port", "587");
        prop.put("mail.smtp.auth", "true");
        prop.put("mail.smtp.starttls.enable", "true"); //TLS

        Session session;
        session = Session.getInstance(prop, new javax.mail.Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(username, password);
            }
        });

        try {

            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress("sendmail.fpttext@gmail.com"));
            message.setRecipients(
                    Message.RecipientType.TO,
                    InternetAddress.parse(txtEmail.getText())
            );
            message.setSubject("HE THONG DAO TAO EDUSYS");
            message.setText("Chào " + nv.getHoTen() + " \n"
                    + "Mã OTP: " + codeSMS);

            Transport.send(message);

            MessegerHelper.alert("Chúng tôi đã gửi mã OTP đến địa chỉ Email trên, \nBạn vui lòng kiểm tra hộp thư!", this);

        } catch (MessagingException e) {
            e.printStackTrace();
            MessegerHelper.alert("Gửi mail thất bại", this);
            return true;
            
        }
        return false;
    }
}
