/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

/**
 *
 * @author XUÂN THÀNH
 */
public class QLChuyenDeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form QLChuyenDeJPanel
     */
    public QLChuyenDeJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlCardQLNhanVien = new javax.swing.JPanel();
        lblQLNhanVienTitle = new javax.swing.JLabel();
        pnlQLNV = new javax.swing.JPanel();
        pnlQLNVInput = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        txtQLNVHoTen = new javax.swing.JTextField();
        lblQLNVHoTen = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblQLNVMaNV = new javax.swing.JLabel();
        txtQLNVMaNV = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txtQLNVSDT = new javax.swing.JTextField();
        lblQLNVSDT = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblQLNVMatKhau = new javax.swing.JLabel();
        txtQLNVMatKhau = new javax.swing.JPasswordField();
        jPanel7 = new javax.swing.JPanel();
        lblQLNVMatKhau2 = new javax.swing.JLabel();
        txtQLNVMatKhau2 = new javax.swing.JPasswordField();
        jPanel9 = new javax.swing.JPanel();
        rdoQLNVTruongPhong = new javax.swing.JRadioButton();
        rdoQLNVNhanVien = new javax.swing.JRadioButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        btnQLNVThem = new javax.swing.JButton();
        btnQLNVSua = new javax.swing.JButton();
        btnQLNVXoa = new javax.swing.JButton();
        btnQLNVMoi = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        btnQLNVFirst = new javax.swing.JButton();
        btnQLNVPre = new javax.swing.JButton();
        btnQLNVNext = new javax.swing.JButton();
        btnQLNVLast = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQLNV = new javax.swing.JTable();

        setBackground(new java.awt.Color(34, 40, 44));

        pnlCardQLNhanVien.setBackground(new java.awt.Color(34, 40, 44));
        pnlCardQLNhanVien.setLayout(new java.awt.BorderLayout());

        lblQLNhanVienTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblQLNhanVienTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblQLNhanVienTitle.setText("QUẢN LÝ CHUYÊN ĐỀ");
        lblQLNhanVienTitle.setPreferredSize(new java.awt.Dimension(382, 50));
        lblQLNhanVienTitle.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlCardQLNhanVien.add(lblQLNhanVienTitle, java.awt.BorderLayout.PAGE_START);

        pnlQLNV.setBackground(new java.awt.Color(34, 40, 44));

        pnlQLNVInput.setBackground(new java.awt.Color(34, 40, 44));
        pnlQLNVInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));
        pnlQLNVInput.setLayout(new java.awt.GridLayout(0, 2));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));
        jPanel1.setLayout(new java.awt.GridLayout(3, 0));

        jPanel8.setBackground(new java.awt.Color(34, 40, 44));

        lblQLNVHoTen.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lblQLNVHoTen.setForeground(new java.awt.Color(255, 255, 255));
        lblQLNVHoTen.setText("Họ và tên");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQLNVHoTen)
                    .addComponent(lblQLNVHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLNVHoTen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQLNVHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel8);

        jPanel3.setBackground(new java.awt.Color(34, 40, 44));

        lblQLNVMaNV.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lblQLNVMaNV.setForeground(new java.awt.Color(255, 255, 255));
        lblQLNVMaNV.setText("Mã nhân viên");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQLNVMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                    .addComponent(txtQLNVMaNV))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLNVMaNV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQLNVMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(34, 40, 44));

        lblQLNVSDT.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lblQLNVSDT.setForeground(new java.awt.Color(255, 255, 255));
        lblQLNVSDT.setText("Số điện thoại");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQLNVSDT)
                    .addComponent(lblQLNVSDT, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLNVSDT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQLNVSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel4);

        pnlQLNVInput.add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));
        jPanel2.setLayout(new java.awt.GridLayout(3, 0));

        jPanel5.setBackground(new java.awt.Color(34, 40, 44));

        lblQLNVMatKhau.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lblQLNVMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        lblQLNVMatKhau.setText("Mật khẩu");

        txtQLNVMatKhau.setPreferredSize(new java.awt.Dimension(7, 30));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtQLNVMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblQLNVMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLNVMatKhau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQLNVMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel5);

        jPanel7.setBackground(new java.awt.Color(34, 40, 44));

        lblQLNVMatKhau2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lblQLNVMatKhau2.setForeground(new java.awt.Color(255, 255, 255));
        lblQLNVMatKhau2.setText("Xác nhận mật khẩu");

        txtQLNVMatKhau2.setPreferredSize(new java.awt.Dimension(7, 30));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQLNVMatKhau2, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                    .addComponent(txtQLNVMatKhau2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLNVMatKhau2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQLNVMatKhau2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel7);

        jPanel9.setBackground(new java.awt.Color(34, 40, 44));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Vai trò", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Arial", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        rdoQLNVTruongPhong.setBackground(new java.awt.Color(34, 40, 44));
        buttonGroup1.add(rdoQLNVTruongPhong);
        rdoQLNVTruongPhong.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        rdoQLNVTruongPhong.setForeground(new java.awt.Color(255, 255, 255));
        rdoQLNVTruongPhong.setText("Trưởng phòng");

        rdoQLNVNhanVien.setBackground(new java.awt.Color(34, 40, 44));
        buttonGroup1.add(rdoQLNVNhanVien);
        rdoQLNVNhanVien.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        rdoQLNVNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        rdoQLNVNhanVien.setSelected(true);
        rdoQLNVNhanVien.setText("Nhân Viên");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdoQLNVTruongPhong)
                .addGap(33, 33, 33)
                .addComponent(rdoQLNVNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoQLNVTruongPhong)
                    .addComponent(rdoQLNVNhanVien))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel9);

        pnlQLNVInput.add(jPanel2);

        jPanel10.setLayout(new java.awt.GridLayout(0, 2));

        jPanel12.setBackground(new java.awt.Color(34, 40, 44));

        btnQLNVThem.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnQLNVThem.setText("Thêm");
        btnQLNVThem.setPreferredSize(new java.awt.Dimension(65, 41));
        jPanel12.add(btnQLNVThem);

        btnQLNVSua.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnQLNVSua.setText("Sửa");
        btnQLNVSua.setPreferredSize(new java.awt.Dimension(65, 41));
        jPanel12.add(btnQLNVSua);

        btnQLNVXoa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnQLNVXoa.setText("Xóa");
        btnQLNVXoa.setPreferredSize(new java.awt.Dimension(65, 41));
        jPanel12.add(btnQLNVXoa);

        btnQLNVMoi.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnQLNVMoi.setText("Mới");
        btnQLNVMoi.setPreferredSize(new java.awt.Dimension(65, 41));
        jPanel12.add(btnQLNVMoi);

        jPanel10.add(jPanel12);

        jPanel11.setBackground(new java.awt.Color(34, 40, 44));

        btnQLNVFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/rnd_br_first.png"))); // NOI18N
        jPanel11.add(btnQLNVFirst);

        btnQLNVPre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/rnd_br_prev.png"))); // NOI18N
        jPanel11.add(btnQLNVPre);

        btnQLNVNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/rnd_br_next.png"))); // NOI18N
        btnQLNVNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNVNextActionPerformed(evt);
            }
        });
        jPanel11.add(btnQLNVNext);

        btnQLNVLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/rnd_br_last.png"))); // NOI18N
        jPanel11.add(btnQLNVLast);

        jPanel10.add(jPanel11);

        tblQLNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ NV", "MẬT KHẨU", "HỌ VÀ TÊN", "VAI TRÒ", "SỐ ĐIỆN THOẠI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblQLNV);

        javax.swing.GroupLayout pnlQLNVLayout = new javax.swing.GroupLayout(pnlQLNV);
        pnlQLNV.setLayout(pnlQLNVLayout);
        pnlQLNVLayout.setHorizontalGroup(
            pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlQLNVLayout.createSequentialGroup()
                .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQLNVLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addComponent(pnlQLNVInput, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlQLNVLayout.setVerticalGroup(
            pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQLNVLayout.createSequentialGroup()
                .addComponent(pnlQLNVInput, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlCardQLNhanVien.add(pnlQLNV, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 903, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pnlCardQLNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pnlCardQLNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLNVNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNVNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQLNVNextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQLNVFirst;
    private javax.swing.JButton btnQLNVLast;
    private javax.swing.JButton btnQLNVMoi;
    private javax.swing.JButton btnQLNVNext;
    private javax.swing.JButton btnQLNVPre;
    private javax.swing.JButton btnQLNVSua;
    private javax.swing.JButton btnQLNVThem;
    private javax.swing.JButton btnQLNVXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblQLNVHoTen;
    private javax.swing.JLabel lblQLNVMaNV;
    private javax.swing.JLabel lblQLNVMatKhau;
    private javax.swing.JLabel lblQLNVMatKhau2;
    private javax.swing.JLabel lblQLNVSDT;
    private javax.swing.JLabel lblQLNhanVienTitle;
    private javax.swing.JPanel pnlCardQLNhanVien;
    private javax.swing.JPanel pnlQLNV;
    private javax.swing.JPanel pnlQLNVInput;
    private javax.swing.JRadioButton rdoQLNVNhanVien;
    private javax.swing.JRadioButton rdoQLNVTruongPhong;
    private javax.swing.JTable tblQLNV;
    private javax.swing.JTextField txtQLNVHoTen;
    private javax.swing.JTextField txtQLNVMaNV;
    private javax.swing.JPasswordField txtQLNVMatKhau;
    private javax.swing.JPasswordField txtQLNVMatKhau2;
    private javax.swing.JTextField txtQLNVSDT;
    // End of variables declaration//GEN-END:variables
}
