/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

/**
 *
 * @author XUÂN THÀNH
 */
public class QLKhoaHocJPanel extends javax.swing.JPanel {

    /**
     * Creates new form QLKhoaHocJPanel
     */
    public QLKhoaHocJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCardQLKhoaHoc = new javax.swing.JPanel();
        pnlQLKHTop = new javax.swing.JPanel();
        lblQLKhoaHocTitle = new javax.swing.JLabel();
        pnlChuyenDe = new javax.swing.JPanel();
        cbbChuyenDe = new javax.swing.JComboBox<>();
        pnlQLKH = new javax.swing.JPanel();

        pnlCardQLKhoaHoc.setBackground(new java.awt.Color(34, 40, 44));
        pnlCardQLKhoaHoc.setLayout(new java.awt.BorderLayout());

        pnlQLKHTop.setBackground(new java.awt.Color(34, 40, 44));
        pnlQLKHTop.setPreferredSize(new java.awt.Dimension(891, 120));
        pnlQLKHTop.setLayout(new java.awt.BorderLayout());

        lblQLKhoaHocTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblQLKhoaHocTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblQLKhoaHocTitle.setText("QUẢN LÝ KHÓA HỌC");
        lblQLKhoaHocTitle.setToolTipText("");
        lblQLKhoaHocTitle.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblQLKhoaHocTitle.setPreferredSize(new java.awt.Dimension(34, 40));
        pnlQLKHTop.add(lblQLKhoaHocTitle, java.awt.BorderLayout.NORTH);

        pnlChuyenDe.setBackground(new java.awt.Color(34, 40, 44));
        pnlChuyenDe.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "CHUYÊN ĐỀ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(255, 102, 102))); // NOI18N

        cbbChuyenDe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnlChuyenDeLayout = new javax.swing.GroupLayout(pnlChuyenDe);
        pnlChuyenDe.setLayout(pnlChuyenDeLayout);
        pnlChuyenDeLayout.setHorizontalGroup(
            pnlChuyenDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChuyenDeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbbChuyenDe, 0, 871, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlChuyenDeLayout.setVerticalGroup(
            pnlChuyenDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChuyenDeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbbChuyenDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pnlQLKHTop.add(pnlChuyenDe, java.awt.BorderLayout.CENTER);

        pnlCardQLKhoaHoc.add(pnlQLKHTop, java.awt.BorderLayout.PAGE_START);

        pnlQLKH.setBackground(new java.awt.Color(34, 40, 44));

        javax.swing.GroupLayout pnlQLKHLayout = new javax.swing.GroupLayout(pnlQLKH);
        pnlQLKH.setLayout(pnlQLKHLayout);
        pnlQLKHLayout.setHorizontalGroup(
            pnlQLKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 903, Short.MAX_VALUE)
        );
        pnlQLKHLayout.setVerticalGroup(
            pnlQLKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );

        pnlCardQLKhoaHoc.add(pnlQLKH, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 903, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pnlCardQLKhoaHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pnlCardQLKhoaHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbbChuyenDe;
    private javax.swing.JLabel lblQLKhoaHocTitle;
    private javax.swing.JPanel pnlCardQLKhoaHoc;
    private javax.swing.JPanel pnlChuyenDe;
    private javax.swing.JPanel pnlQLKH;
    private javax.swing.JPanel pnlQLKHTop;
    // End of variables declaration//GEN-END:variables
}
