/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

/**
 *
 * @author XUÂN THÀNH
 */
public class QLNguoiHocJPanel extends javax.swing.JPanel {

    /**
     * Creates new form QLNguoiHocJPanel
     */
    public QLNguoiHocJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCardQLNguoiHoc = new javax.swing.JPanel();
        lblQLNguoiHocTitle = new javax.swing.JLabel();
        pnlQLNH = new javax.swing.JPanel();

        pnlCardQLNguoiHoc.setBackground(new java.awt.Color(34, 40, 44));
        pnlCardQLNguoiHoc.setLayout(new java.awt.BorderLayout());

        lblQLNguoiHocTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblQLNguoiHocTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblQLNguoiHocTitle.setText("QUẢN LÝ NGƯỜI HỌC");
        lblQLNguoiHocTitle.setToolTipText("");
        lblQLNguoiHocTitle.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblQLNguoiHocTitle.setPreferredSize(new java.awt.Dimension(34, 40));
        pnlCardQLNguoiHoc.add(lblQLNguoiHocTitle, java.awt.BorderLayout.NORTH);

        pnlQLNH.setBackground(new java.awt.Color(34, 40, 44));

        javax.swing.GroupLayout pnlQLNHLayout = new javax.swing.GroupLayout(pnlQLNH);
        pnlQLNH.setLayout(pnlQLNHLayout);
        pnlQLNHLayout.setHorizontalGroup(
            pnlQLNHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 903, Short.MAX_VALUE)
        );
        pnlQLNHLayout.setVerticalGroup(
            pnlQLNHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );

        pnlCardQLNguoiHoc.add(pnlQLNH, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 903, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pnlCardQLNguoiHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pnlCardQLNguoiHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblQLNguoiHocTitle;
    private javax.swing.JPanel pnlCardQLNguoiHoc;
    private javax.swing.JPanel pnlQLNH;
    // End of variables declaration//GEN-END:variables
}
